### PR TITLE
Don't generate an unhandled Deferred.

### PR DESCRIPTION
**Pull request by ldanielburr**
This seemingly tiny change fixes the problem demonstrated at http://stackoverflow.com/questions/9728781/testing-a-failing-job-in-resizabledispatchqueue-with-trial, with all tests still passing.

### CODE REVIEW

**Comment by terrycojones** [comment]
Hi Daniel!  This has bugged me on and off for a couple of years(?), so it's great you've found a concrete problem. I'll make some time on the weekend to think things through and get my head around the code again. (As I said, txRDQ has become too complicated/ambitious, I think.) I'd like to think that I could have only possibly made _one_ error and that you've therefore found it :-) But maybe (as usual) my code is worse than that... Anyway, thanks, and I'll make sure to have a look ASAP.

**Comment by terrycojones** [comment]
Hi Daniel.

I've just spent a little time looking at the code and suggested fix. I think the following snippet (in `_launchJob`) would be better:

``` python
        if job is not self._NOOP:
            result = job.watch()
            self._underway.add(job)
            job.launch(self._func)
            return result
```

That way, `_launchJob` always returns a deferred (unless the job is a no-op). No deferred is re-used (from `job.waiting`). And by requesting a deferred _before_ we launch the job, we avoid the situation in which the job is already finished before `_launchJob` (in its current form) tries to do the rest of its work.

Does that make sense?  It does to me, but I haven't looked at the code enough to be 100% sure.

There seem to be a couple of documentation errors (stuff that's out of date). The docstring on `ResizableDispatchQueue` is about as clear as mud.

**Comment by ldanielburr** [comment]
Hi Terry,

Thanks for having a look at this, I appreciate it.

Your solution makes sense to me, in that it seems like clear and obvious behavior; what I do not understand is whether or not there was a real need for the previous logic (returning the first deferred in the job's waiting list, else new deferred), and if that need now goes unaddressed in the face of this simplification.

For my purposes, I like your change quite well, as it solves the problem and also removes a (to me) confusing second call to job.watch(), which baffled me a bit during debugging, i.e. "why does watch get called twice for the same job, just because the job's state changed?"

Would you like me to make this change in my Pull Request, and add the test from StackOverflow?

**Comment by ldanielburr** [comment]
Hmm, on second thought, I'm curious about something.  Given the code below, why doesn't job.launch return the Deferred that it has created?  Is the docstring wrong in this case?  If job.launch returned this Deferred, then _launchJob would not need to call .watch() at all.

``` python
def launch(self, func):
        """
        Begin operation on this job by passing its job argument to C{func}.
        The call to func is made via defer.maybeDeferred.  When the job
        finishes, its result will be passed on to self.finishedDeferred in
        self._finish below. Arrange to cancel the in-progress work if
        cancel is called on the C{Deferred} we return.

        @param func: the function to call on self.jobarg.

        @raise: C{RuntimeError} if the job is not in the PENDING state.

        @return: A C{Deferred} that will fire (with self) after running
        func on self.jobarg. The result of that call will be in
        self.result.
        """
        if self.state != self.PENDING:
            raise RuntimeError('You cannot launch a job that is not pending.')
        else:
            self.startTime = time.time()
            self.state = self.UNDERWAY
            self._underwayDeferred = defer.maybeDeferred(func, self.jobarg)
            self._underwayDeferred.addCallbacks(self._finished, self._failed)
```

**Comment by ldanielburr** [comment]
Sorry for all the noise, ignore my last 2 comments.

I think this code still has the same problem as the old code, in that it still contains the call to job.watch() which is what creates the addtional Deferred that never gets cleaned up (the first one is created by the call to job.watch() in the .put method).

I should stop speculating and run the tests.

**Comment by terrycojones** [comment]
Actually, I think your code is right. If the job is already done (there is nothing in its `self.waiting`), then `_launchJob` returns `None` and the cooperator moves on immediately once a value comes off the queue.

I don't think it's 100% safe that `_launchJob` re-uses `job.waiting[0]` because the `put` code has returned that same deferred to its calling code. But I guess in practice it's fine and that the cooperator only does transparent things to the deferred (i.e., it passes on the result in the case of success or error).

One thing I wonder about though is why adding a call to job.watch() results in a deferred that is not cleaned up. Why is that? If we solved that, then we could use my approach above and remove the re-use of job.waiting[0].

BTW, one tiny thing, I'd change your `return None` to `pass`. Then both ways for the function to return `None` are the same (i.e., they both fall off the end). Explicitly returning `None` in one case but not in the other seems potentially a bit more confusing.

**Comment by ldanielburr** [comment]
Yeah, I know what you mean about the mystery around watch() generating an unhandled Deferred.  On the one hand, I'd like to figure that out (must be an addErrback somewhere), but on the other hand, I prefer that a call to .put results in one, and only one, call to .watch(), because the symmetry of that makes sense to me.  I guess the call to .watch inside _launchJob would make sense if something internal to txrdq needed to monitor/report on the results of the job, but I don't see that happening anywhere, which is probably why it results in an unhandled Deferred.

I'll change the PR to do pass instead of return None.

**Comment by terrycojones** [comment]
Hi Daniel

OK, I made my own pull request, #5 :-)

I ended up playing with the failing test from the SO posting. That test really should end like this:

``` python
    def test_txrdq(self):
        self.queue = ResizableDispatchQueue(self.aFailingJob, 1)
        return self.failUnlessFailure(self.queue.put('Some argument', 1), Job)
```

I realized it's right to call `addErrback` on the result of `watch`. We're already handling the result of the job processing (in `put`). In `_launchJob` you always want to return a deferred because you want the cooperator to wait for the outstanding job to finish. Calling watch again is cleaner, and it also allows us to hide the `job.waiting` list, which is good.

Can you take a look at the pull request?  I am happy for you to merge or cherry pick my code into your pull request & we can merge yours. You found the problem, and should be credited with it, etc.  I just added an AUTHORS file to #5 and put you in it too. Good?

**Comment by terrycojones** [comment]
BTW, I think your solution (and the comment you added) is exactly right. I'm happy to go with that if you like. Not looking in job.waiting is maybe slightly better/cleaner though.

**Comment by ldanielburr** [comment]
I think I'm fine with either my solution or yours.  As the creator of txrdq, I think your design preference should take precedence over my own.

How about I close #4 and add a test for this behavior to #5 ?

**Comment by ldanielburr** [comment]
Actually, I can't close #4, so would you mind closing it for me?  Thanks.

**Comment by ldanielburr** [comment]
Never mind, apparently I'm just very bad at github.

**Pull request closed without merging**
