### PR TITLE
Don't allow a failure to go unhandled in a deferred

### PR DESCRIPTION
**Pull request by terrycojones**
Add an addErrback to ignore any error in the deferred we get from watching a launched a job. Hide the 'waiting' list on a job as we no longer need to access it. Cleaned up job docstring a little.

All the debugging & thinking to find this problem was done by @ldanielburr

Fixes #4

### CODE REVIEW

**Comment by ldanielburr** [comment]
How about we add the unit-test for this to test_rdq.py?  Something like:

``` python
class TestDeferredHandling(unittest.TestCase):
    def _raiseException(self, a):
        raise Exception('An exception occurred.')

    def setUp(self):
        self.queue = ResizableDispatchQueue(self._raiseException, 1)

    def tearDown(self):
        pass

    def test_txrdq(self):
        d = self.queue.put("Some argument", 1)
        d = self.assertFailure(d, Job)
        return d
```

**Comment by terrycojones** [comment]
OK, I added two tests (which could have been one). If you're good with all this I'll merge and push it to PyPI.

**Comment by ldanielburr** [comment]
Looks good to me, thanks for resolving this so swiftly.

**Comment by terrycojones** [comment]
Ha - you're calling 3 years swiftly???  And... YOU resolved it :-)

**Comment by terrycojones** [comment]
OK, 0.2.14 is on PyPI
https://pypi.python.org/pypi/txRDQ/0.2.14

**Pull request merged**
